spring:
  application:
    name: ideasystem
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/ideasystem?useTimezone=true&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  # Movido para fora de jpa:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none # Excelente: agora o Flyway assume o controle
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false